// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmazjpvoictkcpnbcqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtYXpqcHZvaWN0a2NwbmJjcXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDE1NTcsImV4cCI6MjA2NDIxNzU1N30.-sowJsz_9DXzDw1upv00YriHLGxUkDy-9JwcYG0tNtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);